# Generated by Django 5.0.6 on 2025-06-09 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_teamseasonparticipation'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fanprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='user',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='coach_profiles/')),
                ('coach', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.coach')),
                ('player', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.player')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CoachProfile',
        ),
        migrations.DeleteModel(
            name='FanProfile',
        ),
        migrations.DeleteModel(
            name='PlayerProfile',
        ),
    ]
