# Generated by Django 5.2.2 on 2025-07-18 10:33

from django.db import migrations


def migrate_roles(apps, schema_editor):
    User = apps.get_model('users', 'User')

    for user in User.objects.all():
        if user.is_admin:
            user.role = 'admin'
        elif user.is_coach:
            user.role = 'coach'
        elif user.is_player:
            user.role = 'player'
        else:
            user.role = 'fan'
        user.save()

class Migration(migrations.Migration):


    dependencies = [
        ('users', '0004_user_is_admin_alter_userprofile_image'),
    ]

    operations = [
    ]
