# Generated by Django 5.2.2 on 2025-07-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_convert_roles_to_single_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_coach',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_fan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_player',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('player', 'Player'), ('coach', 'Coach'), ('fan', 'Fan')], default='fan', max_length=10),
        ),
    ]
