# Generated by Django 5.2.2 on 2025-10-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0017_lineup_formation'),
        ('users', '0009_alter_user_managers_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_teams',
            field=models.ManyToManyField(blank=True, related_name='followers', to='league.team'),
        ),
    ]
