# Generated by Django 5.2.2 on 2025-11-09 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0019_teamoftheweek_teamoftheweekplayer_and_more'),
        ('users', '0010_userprofile_favorite_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.match'),
        ),
    ]
