# Generated by Django 5.2.2 on 2025-08-13 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0001_initial'),
        ('league', '0014_player_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fantasy_match_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='fantasy.fantasymatchweek')),
                ('fantasy_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='fantasy.fantasyteam')),
                ('player_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='league.player')),
                ('player_out', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='league.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
