# Generated by Django 5.2.2 on 2025-08-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0002_fantasytransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyleague',
            name='sell_price_policy',
            field=models.CharField(choices=[('purchase', 'Refund at purchase price'), ('current', 'Refund at current price')], default='purchase', help_text='How to compute refund when removing a player', max_length=16),
        ),
    ]
