# Generated by Django 5.2.2 on 2025-08-13 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0003_fantasyleague_sell_price_policy'),
        ('league', '0014_player_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasytransfer',
            name='action',
            field=models.CharField(choices=[('add', 'Add'), ('remove', 'Remove'), ('swap', 'Swap')], default='add', max_length=10),
        ),
        migrations.AlterField(
            model_name='fantasytransfer',
            name='player_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='league.player'),
        ),
        migrations.AddConstraint(
            model_name='fantasyteam',
            constraint=models.UniqueConstraint(fields=('user', 'fantasy_league'), name='unique_team_per_user_per_league'),
        ),
    ]
