# Generated by Django 5.2.2 on 2025-06-15 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_teamseasonparticipation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'verbose_name_plural': 'Leagues'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterModelOptions(
            name='teamseasonparticipation',
            options={'ordering': ['-points', '-goals_scored', 'goals_conceded']},
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AlterUniqueTogether(
            name='teamseasonparticipation',
            unique_together={('team', 'league')},
        ),
        migrations.AddField(
            model_name='coach',
            name='bio',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='personel_photos/'),
        ),
        migrations.AddField(
            model_name='coach',
            name='role',
            field=models.CharField(choices=[('H', 'Head Coach'), ('A', 'Assistant Coach')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('SCH', 'Scheduled'), ('LIV', 'Live'), ('FIN', 'Finished'), ('CAN', 'Cancelled')], default='SCH', max_length=3),
        ),
        migrations.AddField(
            model_name='player',
            name='bio',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='teamseasonparticipation',
            name='draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseasonparticipation',
            name='goals_conceded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseasonparticipation',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseasonparticipation',
            name='matches_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coach',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaches', to='league.team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='personel_photos/'),
        ),
        migrations.AlterUniqueTogether(
            name='playerstats',
            unique_together={('match', 'player')},
        ),
        migrations.CreateModel(
            name='CoachSeasonParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('left_at', models.DateField(blank=True, null=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.coach')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSeasonParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('red_cards', models.IntegerField(default=0)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('left_at', models.DateField(blank=True, null=True)),
                ('is_captain', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.team')),
            ],
        ),
        migrations.AddField(
            model_name='playerstats',
            name='player_participation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='league.playerseasonparticipation'),
        ),
        migrations.AddIndex(
            model_name='playerstats',
            index=models.Index(fields=['match', 'player'], name='league_play_match_i_7f2a40_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstats',
            index=models.Index(fields=['player_participation'], name='league_play_player__e8a7bd_idx'),
        ),
        migrations.RemoveField(
            model_name='teamseasonparticipation',
            name='position',
        ),
        migrations.AlterUniqueTogether(
            name='coachseasonparticipation',
            unique_together={('coach', 'team', 'league')},
        ),
        migrations.AlterUniqueTogether(
            name='playerseasonparticipation',
            unique_together={('player', 'team', 'league')},
        ),
    ]
