# Generated by Django 5.2.2 on 2025-06-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_alter_league_options_alter_team_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='assists',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='goals',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='red_cards',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='yellow_cards',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
