# Generated by Django 5.2.2 on 2025-06-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_alter_playerstats_assists_alter_playerstats_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
