# Generated by Django 5.2.2 on 2025-07-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_coach_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name_plural': 'Coaches'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='playerstats',
            options={'verbose_name_plural': 'Player Stats'},
        ),
    ]
