# Generated by Django 5.2.2 on 2025-07-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_alter_coach_options_alter_match_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_day',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
