# Generated by Django 5.2.2 on 2025-07-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_lineup'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='playerstats',
            name='league_play_player__e8a7bd_idx',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='player_participation',
        ),
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['season'], name='league_matc_season__6fa7d6_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['home_team', 'away_team'], name='league_matc_home_te_a513b1_idx'),
        ),
    ]
