# Generated by Django 5.2.2 on 2025-07-22 21:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_remove_playerstats_league_play_player__e8a7bd_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
