# Generated by Django 5.2.2 on 2025-07-24 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_league_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='team',
        ),
    ]
