# Generated by Django 5.2.2 on 2025-07-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_remove_coach_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerseasonparticipation',
            name='clean_sheets',
            field=models.IntegerField(default=0),
        ),
    ]
