# Generated by Django 5.2.2 on 2025-07-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_playerseasonparticipation_clean_sheets'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='actual_kickoff_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
