# Generated by Django 5.2.2 on 2025-08-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_match_actual_kickoff_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Market price for fantasy budget calculations', max_digits=10),
        ),
    ]
