# Generated by Django 5.2.2 on 2025-08-18 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0015_matchevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineupPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starter', models.BooleanField(default=True, help_text='Is this player in the starting lineup?')),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.lineup')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.player')),
            ],
            options={
                'ordering': ['-is_starter', 'player__last_name'],
                'unique_together': {('lineup', 'player')},
            },
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='players',
        ),
        migrations.AddField(
            model_name='lineup',
            name='players',
            field=models.ManyToManyField(related_name='lineups', through='league.LineupPlayer', to='league.player'),
        ),
    ]
