# Generated by Django 5.2.2 on 2025-08-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0016_lineupplayer_alter_lineup_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='formation',
            field=models.CharField(blank=True, default='4-4-2', max_length=10, null=True),
        ),
    ]
