# Generated by Django 5.2.2 on 2025-10-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0017_lineup_formation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineupplayer',
            options={'ordering': ['-is_starter', 'position']},
        ),
        migrations.AddField(
            model_name='lineupplayer',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='The order of the player in the lineup (0-10 for starters)'),
        ),
    ]
