# Generated by Django 5.2.2 on 2025-11-03 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0018_alter_lineupplayer_options_lineupplayer_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamOfTheWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
            ],
        ),
        migrations.CreateModel(
            name='TeamOfTheWeekPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Forward')], default='DEF', max_length=3)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.player')),
                ('team_of_the_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.teamoftheweek')),
            ],
        ),
        migrations.AddField(
            model_name='teamoftheweek',
            name='players',
            field=models.ManyToManyField(related_name='teams_of_the_week', through='league.TeamOfTheWeekPlayer', to='league.player'),
        ),
        migrations.AlterUniqueTogether(
            name='teamoftheweek',
            unique_together={('league', 'week_number')},
        ),
    ]
