# Generated by Django 5.2.2 on 2025-08-12 13:01

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_update_invitation_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invitation',
            new_name='content_inv_email_d1f103_idx',
            old_name='content_in_email_is_exp_123abc_idx',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=content.models.default_expiry),
        ),
    ]
